name: driving_license_exam
description: A comprehensive driving license exam preparation application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  
  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  
  # Local Storage
  path_provider: ^2.1.5
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  flutter_html: ^3.0.0-alpha.6
  flutter_html_all: ^3.0.0-alpha.6
  
  # Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  collection: ^1.19.0
  shared_preferences: ^2.3.5
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  package_info_plus: ^8.1.2
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/data/
    - assets/icons/ic_app_logo.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/ic_app_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/ic_app_logo.png
  color_dark: "#1A237E"
  image_dark: assets/icons/ic_app_logo.png
  
  android_12:
    image: assets/icons/ic_app_logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icons/ic_app_logo.png
    icon_background_color_dark: "#1A237E"

  web: false
  ios: true
  android: true
  fullscreen: true


